// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI23H7H4P-iVe-ZNDBdKljYlCnxZI3JEw',
    appId: '1:282714124997:web:13fc96eb7b6fe58c9436ac',
    messagingSenderId: '282714124997',
    projectId: 'ouvsysteme',
    authDomain: 'ouvsysteme.firebaseapp.com',
    storageBucket: 'ouvsysteme.firebasestorage.app',
    measurementId: 'G-VQQ2VM7WTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ73H9kmgNeHH1LXruMEGZDo2x3yo5fCU',
    appId: '1:282714124997:android:a2e8b555346429f49436ac',
    messagingSenderId: '282714124997',
    projectId: 'ouvsysteme',
    storageBucket: 'ouvsysteme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvs-2a2f8sDg9-KtsiQOHPo3hPW928fvU',
    appId: '1:282714124997:ios:5b010ab5ab03074a9436ac',
    messagingSenderId: '282714124997',
    projectId: 'ouvsysteme',
    storageBucket: 'ouvsysteme.firebasestorage.app',
    iosClientId: '282714124997-gamu12r0gckq87lvakt6ka010oo73tfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ouvDooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvs-2a2f8sDg9-KtsiQOHPo3hPW928fvU',
    appId: '1:282714124997:ios:5b010ab5ab03074a9436ac',
    messagingSenderId: '282714124997',
    projectId: 'ouvsysteme',
    storageBucket: 'ouvsysteme.firebasestorage.app',
    iosClientId: '282714124997-gamu12r0gckq87lvakt6ka010oo73tfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ouvDooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI23H7H4P-iVe-ZNDBdKljYlCnxZI3JEw',
    appId: '1:282714124997:web:601c40bc4fc81e6f9436ac',
    messagingSenderId: '282714124997',
    projectId: 'ouvsysteme',
    authDomain: 'ouvsysteme.firebaseapp.com',
    storageBucket: 'ouvsysteme.firebasestorage.app',
    measurementId: 'G-C8RC4V7SCB',
  );
}
